services:
  server:
    build:
      context: ./server
    container_name: server_container
    ports:
      - "4000:4000" # Expose the API on port 4000
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - mysql
    networks:
      - brighte-eats

  client:
    build:
      context: ./client
    container_name: client_container
    ports:
      - "3000:3000" # Expose the API on port 4000
    depends_on:
      - server
    networks:
      - brighte-eats

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - brighte-eats

volumes:
  mysql_data:

networks:
  brighte-eats:
    driver: bridge
